name: chicago_rent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - matplotlib
  - shapely
  - pyproj
  - pip
  - pip:
    - altair
    - vl-convert-python
    - streamlit
